version: '3.8'

services:
  pricing-api:
    build:
      context: ../
      dockerfile: infra/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - esoluzion-network

  pricing-console:
    build:
      context: ../
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - pricing-api
    networks:
      - esoluzion-network

networks:
  esoluzion-network:
    driver: bridge
